ARG version
FROM almalinux:${version:-9}
ENV course="devops"\
    duration="120 hours"
ARG trainer="siva"
RUN echo "hi , COURSE is : ${course},DURATION : ${duration}, TRAINER: ${trainer}"
CMD [ "sleep","1000" ]
